name: dart_backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dotenv: ^4.0.1
  postgres: ^2.5.2
  shelf: ^1.4.0
  shelf_modular: ^2.0.1
  shelf_plus: ^1.5.0
  shelf_router: ^1.1.3
